### ISSUE TITLE
Upgrade node-hid dependency to 0.4.0

### ISSUE THREAD

**Issue by dropdevcoding** [terox/urweather#1]
Since I want to use urweather on a raspberry pi which had installed node 0.12.x and node-hid didn't compile (as you already mentioned in the docs) I did a bit of research and found out that node-hid is currently working on node 0.12.x using node-hid 0.4.0. Could you update the dependency for it?

**Comment by terox** [comment]
Sorry the delay. I haven't see the issue.

Could you send your changes as a PR? I have seen that you changed it in your fork.

Thank you very much!

**Comment by terox** [comment]
PR merged and updated README.

We still in touch for improve the project!

Thank you very much!
